services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    volumes:
      - ./src:/app/src   # 로컬 디렉토리를 컨테이너의 디렉토리와 연결
      - ./target:/app/target
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: "mysql:latest"
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  app-network:

volumes:
  db-data:
